import { initNav } from "./scripts/nav.js";
import { initHeroIntro } from "./scripts/hero-intro.js";
import { initHeroWords } from "./scripts/hero-words.js";
import { initHeroCompare } from "./scripts/hero-compare.js";
import { initAccordion, initProcessProgress } from "./scripts/accordion.js";
import { initTimeline } from "./scripts/timeline.js";
import { initResultCarousel, initResultReveal } from "./scripts/carousel.js";
import { initCounters } from "./scripts/counters.js";
import { initReveal, initRevealUp, initRevealProcess } from "./scripts/reveal.js";
import { initCursor } from "./scripts/cursor.js";
import { initGoals } from "./scripts/goals.js";
import { initAriaDisabled, initEmailLinks } from "./scripts/interactions.js";

initNav();
initHeroIntro();
initHeroWords();
initHeroCompare();
initAccordion();
initProcessProgress();
initTimeline();
initResultCarousel();
initResultReveal();
initCounters();
initReveal();
initRevealUp();
initRevealProcess();
initCursor();
initGoals();
initAriaDisabled();
initEmailLinks();
